import { PermissionFlags, PlatformRole } from '../types';

export const DEFAULT_PERMISSIONS: Record<PlatformRole, PermissionFlags> = {
  Admin: {
    view_all_cases: true,
    view_department_cases: true,
    create_cases: true,
    edit_own_cases: true,
    edit_all_cases: true,
    resolve_cases: true,
    assign_cases: true,
    submit_handover: true,
    complete_checklist: true,
    manage_staff: true,
    manage_checklists: true,
    view_audit_logs: true,
    manage_settings: true,
  },
  'Duty Manager': {
    view_all_cases: true,
    view_department_cases: true,
    create_cases: true,
    edit_own_cases: true,
    edit_all_cases: true,
    resolve_cases: true,
    assign_cases: true,
    submit_handover: true,
    complete_checklist: true,
    manage_staff: false,
    manage_checklists: true,
    view_audit_logs: false,
    manage_settings: false,
  },
  'Department Lead': {
    view_all_cases: false,
    view_department_cases: true,
    create_cases: true,
    edit_own_cases: true,
    edit_all_cases: true,
    resolve_cases: true,
    assign_cases: true,
    submit_handover: false,
    complete_checklist: true,
    manage_staff: false,
    manage_checklists: true,
    view_audit_logs: false,
    manage_settings: false,
  },
  Staff: {
    view_all_cases: false,
    view_department_cases: true,
    create_cases: true,
    edit_own_cases: true,
    edit_all_cases: false,
    resolve_cases: false,
    assign_cases: false,
    submit_handover: false,
    complete_checklist: true,
    manage_staff: false,
    manage_checklists: false,
    view_audit_logs: false,
    manage_settings: false,
  },
  Viewer: {
    view_all_cases: true,
    view_department_cases: true,
    create_cases: false,
    edit_own_cases: false,
    edit_all_cases: false,
    resolve_cases: false,
    assign_cases: false,
    submit_handover: false,
    complete_checklist: false,
    manage_staff: false,
    manage_checklists: false,
    view_audit_logs: false,
    manage_settings: false,
  },
};

export function can(permissions: PermissionFlags | undefined, flag: keyof PermissionFlags): boolean {
  return permissions?.[flag] === true;
}
